blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index,name="blogHome"),
    path("blogpost/<int:id>", views.blogpost,name="blogPost"),
    path("search/",views.search,name="Search"),
    path("filtered/",views.filters,name="Filter"),
    path('signup/',views.handleSignup,name='handleSignup'),
    path('login/',views.handleLogin,name='handleLogin'),
    path('logout/',views.handleLogout,name='handleLogout'),
    path('toggle-like/',views.toggle_like,name='toggleLike'),
]

buyCart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("",views.index),
    path('admin/', admin.site.urls),
    path("shop/",include('shop.urls')),
    path("blog/",include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index,name="ShopHome"),
    path("about/", views.about,name="AboutUs"),
    path("contact/", views.contact,name="ContactUs"),
    path("tracker/", views.tracker,name="TrackingStatus"),
    path("search/", views.search,name="Search"),
    path("products/<int:myid>", views.productView,name="ProductView"),
    path("checkout/", views.checkout,name="Checkout"),
    path('signup/',views.handleSignup,name='handleSignup'),
    path('login/',views.handleLogin,name='handleLogin'),
    path('logout/',views.handleLogout,name='handleLogout'),
    path('gateway/',views.handlePayment,name='gateway'),
    path('rating/',views.rateProduct,name='rating'),
    path('filter/',views.filters,name='filters'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    product_name=models.CharField(max_length=200)
    category= models.CharField(max_length=50,default="")
    subcategory= models.CharField(max_length=50,default="")
    available_sizes = models.CharField(max_length=100,help_text="Enter sizes comma separated. Example: S,M,L or 6,7,8,9",default="")
    price=models.IntegerField(default=0,help_text="Enter MRP on Product")
    discount=models.IntegerField(default=0,help_text="Enter discount in percentage")
    finalPrice=models.IntegerField(default=0,editable=False)
    desc=models.CharField(max_length=100000)
    pub_date=models.DateField()
    main_image = models.ImageField(upload_to="shop/images")
    prodRating = models.FloatField(default=0.0)
    ratingCount = models.IntegerField(default=0)
    
    def save(self, *args,**kwargs):
        if (not self.discount) or (self.discount==0):
            self.finalPrice=self.price
        elif self.price:
            self.finalPrice=self.price-int((self.price*self.discount/100))-1
        self.available_sizes = self.available_sizes.upper().replace(" ", "")
        super().save(*args,**kwargs)

    def __str__(self):
        return self.product_name
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name="extra_images")
    image = models.ImageField(upload_to="shop/product_images")

    def __str__(self):
        return f"Image of {self.product.product_name}"

class Contact(models.Model):
    msg_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    email= models.CharField(max_length=50,default="")
    phone= models.CharField(max_length=13,default="")
    desc=models.CharField(max_length=2000,default="")
    timeStamp=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Order(models.Model):
    order_id=models.AutoField(primary_key=True)
    items_json=models.CharField(max_length=5000)
    amount=models.FloatField(default=0.0)
    name=models.CharField(max_length=90)
    email=models.CharField(max_length=120)
    address=models.CharField(max_length=200)
    city=models.CharField(max_length=120)
    state=models.CharField(max_length=60)
    zip_code=models.CharField(max_length=6)
    phone_no=models.CharField(max_length=15)
    payment_status=models.CharField(max_length=25,default="")
class OrderUpdate(models.Model):
    update_id=models.AutoField(primary_key=True)
    order_id=models.IntegerField(default=0)
    update_desc=models.CharField(max_length=5000)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.order_id)+" : "+ self.update_desc
    
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField()
    review = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('product', 'user')

shop/views.py
from math import ceil
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Product,Contact,Order,OrderUpdate,Rating
import json
from collections import defaultdict
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    allProds=[]
    catProds=Product.objects.values('category','id')

    cat_sub_map = defaultdict(set)
    for item in Product.objects.values('category', 'subcategory'):
        cat_sub_map[item['category']].add(item['subcategory'])

    cat_sub_map = {k: list(v) for k, v in cat_sub_map.items()}

    cats={item['category'] for item in catProds}
    for cat in cats:
        prod=Product.objects.filter(category=cat)
        n=len(prod)
        nSlides=n//4 + ceil((n/4)-(n//4))
        allProds.append([prod, range(1,nSlides),nSlides])
    
    available_Cats=Product.objects.values('category').distinct()
    available_subCats=Product.objects.values('subcategory').distinct()
    
    params={'allProds':allProds,'available_Cats':available_Cats,'available_subCats':available_subCats,'categories':"AllCats",'subCategories':"AllSubs",'sizes':"AllSizes",'ratings':"AllRates",'priceRange':"AllPrices",'cat_sub_map': json.dumps(cat_sub_map)}  

    return render(request,'shop/index.html',params)

def filters(request):
    if request.method=="POST":
        products=Product.objects.all()
        cat_sub_map = defaultdict(set)

        for item in Product.objects.values('category', 'subcategory'):
            cat_sub_map[item['category']].add(item['subcategory'])

        cat_sub_map = {k: list(v) for k, v in cat_sub_map.items()}

        categories=request.POST.get('categories')
        subCategories=request.POST.get('subCategories')
        sizes=request.POST.get('sizes')
        ratings=request.POST.get('ratings')
        priceRange=request.POST.get('priceRange')
        if categories=="AllCats" and subCategories=="AllSubs" and sizes=="AllSizes" and ratings=="AllRates" and priceRange=="AllPrices":
            return redirect('ShopHome')
        if categories and categories!="AllCats":
            products=products.filter(category=categories)
        if subCategories and subCategories!="AllSubs":
            products=products.filter(subcategory=subCategories)

        if sizes and sizes != "AllSizes":
            products = products.filter(available_sizes__icontains=sizes)

        if ratings and ratings != "AllRates":
            if ratings == "2":
                products = products.filter(prodRating__lte=3)
            else:
                products = products.filter(prodRating__gte=int(ratings))

        if priceRange and priceRange != "AllPrices":
            priceRange = int(priceRange)
            if priceRange == 500:
                products = products.filter(finalPrice__lte=500)
            elif priceRange == 1000:
                products = products.filter(finalPrice__gt=500, finalPrice__lte=1000)
            elif priceRange == 2000:
                products = products.filter(finalPrice__gt=1000, finalPrice__lte=2000)
            elif priceRange == 5000:
                products = products.filter(finalPrice__gt=2000, finalPrice__lte=5000)
            elif priceRange == 6000:
                products = products.filter(finalPrice__gte=5000)
        
        cats = products.values_list('category', flat=True).distinct()
        allProds=[]
        available_Cats=Product.objects.values('category').distinct()
        available_subCats=Product.objects.values('subcategory').distinct()
        
        if not cats:
            messages.error(request,"No Products Found")
            return render(request, "shop/index.html", {'allProds':allProds,'available_Cats':available_Cats,'available_subCats':available_subCats,'categories':categories,'subCategories':subCategories,'sizes':sizes,'ratings':ratings,'priceRange':priceRange,'cat_sub_map': json.dumps(cat_sub_map)})
        
        for cat in cats:
            prod=products.filter(category=cat)
            n=len(products)
            nSlides=n//4 + ceil((n/4)-(n//4))
            allProds.append([prod, range(1,nSlides),nSlides])
    
    
        params={'allProds':allProds,'available_Cats':available_Cats,'available_subCats':available_subCats,'categories':categories,'subCategories':subCategories,'sizes':sizes,'ratings':ratings,'priceRange':priceRange,'cat_sub_map': json.dumps(cat_sub_map)}
    
        return render(request, "shop/index.html", params)

    return redirect('ShopHome')
        
    

def searchMatch(query,item):
    if query in item.product_name.lower() or query in item.desc.lower() or query in item.category.lower() or query in item.subcategory.lower():
        return True
    else:
        return False

def search(request):
    query=request.GET.get('search')
    allProds=[]
    catProds=Product.objects.values('category','id')
    cats={item['category'] for item in catProds}
    for cat in cats:
        prodtemp=Product.objects.filter(category=cat)
        prod=[item for item in prodtemp if searchMatch(query,item)]
        n=len(prod)
        nSlides=n//4 + ceil((n/4)-(n//4))
        if len(prod)!=0:
            allProds.append([prod, range(1,nSlides),nSlides])
    params={'allProds':allProds}
    if len(allProds)==0 or len(query)<2:
        params={}
        messages.error(request,"No Match Found")
        return redirect('ShopHome')
    return render(request,'shop/search.html',params)

def about(request):
    return render(request,'shop/about.html')

def contact(request):
    if request.user.is_authenticated:
        prevMsgs=Contact.objects.filter(email=request.user.email).order_by('-timeStamp')
        if request.method=="POST":
            name=request.POST.get('name')
            email=request.POST.get('email')
            phone=request.POST.get('phone','')
            desc=request.POST.get('desc','')
            contact=Contact(name=name,email=email,phone=phone,desc=desc)
            contact.save()
            messages.success(request,"Your message has been sent")
            return render(request,'shop/contact.html',{'prevMsgs':prevMsgs})
    else:
        prevMsgs=[]
        messages.error(request,"Login To Contact Us or To View Previous Messages")
   
    return render(request,'shop/contact.html',{'prevMsgs':prevMsgs})

def tracker(request):

    if request.user.is_authenticated:
        Order.objects.filter(email=request.user.email,payment_status__in=["", "pending"]).delete()
        try:
            email = request.user.email
            orders = Order.objects.filter(email=email)
            if len(orders) > 0:
                finalDict = {}
                for prod in orders:
                    products_list = []
                    try:
                        items = json.loads(prod.items_json)
                        for item_key, item_data in items.items():
                            pid = item_key.replace('pr', '')   
                            try:
                                product = Product.objects.get(id=pid)
                                products_list.append({
                                    "name": product.product_name,
                                    "qty": item_data[0],          
                                    "price": product.finalPrice,
                                    "image": product.main_image.url,
                                    "size": item_data[3],
                                })
                            except Product.DoesNotExist:
                                pass
                    except Exception:
                        products_list = []

                    orderId = prod.order_id
                    update_qs = OrderUpdate.objects.filter(order_id=orderId)
                    updates = []
                    for item in update_qs:
                        updates.append({
                            'text': item.update_desc,
                            'time': item.timestamp,
                        })
                    finalDict[prod] = {
                        "updates": updates,
                        "products": products_list,
                    }
                return render(request, 'shop/tracker.html', {"finalDict": finalDict})
            else:
                messages.success(request, "You did not order anything...")
                return render(request, 'shop/tracker.html', {"finalDict": {}})
        except Exception as e:
            print("Tracker error:", e)
            messages.error(request, "Unable to fetch your orders...")
            return render(request, 'shop/tracker.html', {"finalDict": {}})
    else:
        messages.error(request, "Login to track your orders...")
    return render(request, 'shop/tracker.html', {"finalDict": {}})

def productView(request,myid):
    product=Product.objects.filter(id=myid)
    return render(request,'shop/prodView.html', {'product':product[0]})

def checkout(request):
    if request.method=="POST":
        items_json=request.POST.get('itemsJson','')
        name = request.user.get_full_name()
        email = request.user.email
        amount=request.POST.get('amount','')
        address=request.POST.get('address1','')+ " " + request.POST.get('address2','')
        city=request.POST.get('city','')
        state=request.POST.get('state','')
        zip_code=request.POST.get('zip_code','')
        phone=request.POST.get('phone','')
        try:
            order=Order(items_json=items_json,name=name,amount=amount,email=email,phone_no=phone,address=address,city=city,state=state,zip_code=zip_code,payment_status="")
            order.save()
            update=OrderUpdate(order_id=order.order_id,update_desc="The order has been placed")
            update.save()
            dummy=request.POST.get('dummy','false')

shop/templates/shop/about.html
{% extends 'shop/basic.html' %}
{% load static %}
{% block title %} About Us {% endblock %}
{%block about%}active{%endblock about%}
{% block body %}
{%block css%}
<style>
    .card1{
       background: linear-gradient(90deg, #F3C4FB 0%, #A5F3FC 45%, #D1E8FF 100%); 
       border: 2px solid blue;
    }
    .btn-outline-light{
        width: 200px;
        border: 2px solid blue;
    }
    </style>
{% endblock %}
<main style="margin-top: 60px!important;">
    <div class="container py-4">
        <header class="pb-3 mb-4 border-bottom"  > 
            <a href="/shop/about" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                <span class="fs-4">About Us</span> 
            </a> 
        </header>

        <div class="p-5 mb-4 bg-body-tertiary rounded-3">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">buyCart</h1>
                <p class="col-md-8 fs-4">I am A. A. Shaikh, the developer of the BuyCart website. I am currently learning Django, and this project is an important part of my learning journey and practical skill development.</p> 
                <button class="btn btn-primary btn-lg" type="button">Learn More</button>
            </div>
        </div>
        <div class="row align-items-md-stretch">
            <div class="col-md-6">
                <div class="h-100 p-5 text-dark-emphasis rounded-3 card1 h-100 d-flex flex-column justify-content-center">
                    <h2>Change the background</h2>
                    <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look.
                        Then, mix and match with additional component themes and more.</p> <button
                        class="btn btn-outline-light bg-light text-dark-emphasis mx-auto mt-auto " type="button">Example button</button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="h-100 p-5 text-dark-emphasis rounded-3 card1 h-100 d-flex flex-column justify-content-center">
                    <h2>Add borders</h2>
                    <p>Or, keep it light and add a border for some added definition to the boundaries of your content.
                        Be sure to look under the hood at the source HTML here as we've adjusted the alignment and
                        sizing of both column's content for equal-height.</p> 
                        <button class="btn btn-outline-light bg-light text-dark-emphasis mx-auto mt-auto" type="button">Example button</button>
                </div>
            </div>
        </div>
        <footer class="pt-3 mt-4 text-body-secondary border-top">&copy; 2025 </footer>
    </div>
</main>
{% endblock %}
{% block js %}
    <script src="{% static 'shop/js/cart.js' %}"></script>
{% endblock %}

shop/templates/shop/prodView.html
{% extends 'shop/basic.html' %}
{% load static %}
{% load splitTag %}
{%block home%}active{%endblock home%}
{% block title %} {{product.product_name}} - buyCart {% endblock %}
{% block css %}
<style>
  .description {
    background: linear-gradient(90deg, #F3C4FB 0%, #A5F3FC 45%, #D1E8FF 100%);
    border-radius: 20px;
    border: 3px solid blue;
    display: flex;
    flex-direction: column;

  }

  .descIn {
    max-height: 300px;
    overflow-y: auto;
  }

  .divpr {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 250px;
    height: 50px;
  }

  .star-rating::after {
    content: "⭐⭐⭐⭐⭐";
    --rating-percent: calc(attr(data-rating type(<number>), 0) / 5 * 100%);
    background: linear-gradient(90deg, gold var(--rating-percent), grey var(--rating-percent));
    color: transparent;
    background-clip: text;
  }

  #review {
    border: 2px solid black;
    outline: none;
    border-radius: 5px;
    padding: 5px 5px !important;
  }

  #review:focus {
    outline: none;
    border: 2px solid blue;
  }

  select {
    text-align: center;
    text-align-last: center;
  }

  .carousel-control-prev-icon,
  .carousel-control-next-icon {
    background-image: none;
    width: 40px;
    height: 40px;
    background-color: black;
    border-radius: 50%;
    position: relative;
  }


  .carousel-control-prev-icon::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 12px;
    height: 12px;
    border-left: 3px solid white;
    border-bottom: 3px solid white;
    transform: translate(-40%, -50%) rotate(45deg);
  }


  .carousel-control-next-icon::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 12px;
    height: 12px;
    border-right: 3px solid white;
    border-top: 3px solid white;
    transform: translate(-60%, -50%) rotate(45deg);
  }

  .carousel-indicators button {
    background-color: black !important;
    width: 8px;
    height: 8px;
    border-radius: 50%;
  }

  .carousel-indicators .active {
    background-color: black !important;
  }

  .carousel-control-prev,
  .carousel-control-next {
    opacity: 0.6;
  }

  .carousel-control-prev:hover,
  .carousel-control-next:hover {
    opacity: 1;
  }
</style>
{% endblock css %}
{% block body %}
<div class="container text-secondary-emphasis my-4" style="margin-top: 70px!important;">
  <a class="btn btn-primary" href="/shop/" style="text-decoration: none">&#x2190;Home</a>
  <div class="row">
    <div class="col-md-4">
      <div id="productCarousel" class="carousel slide" data-bs-ride="carousel">

        <div class="carousel-indicators">
          <button type="button" data-bs-target="#productCarousel" data-bs-slide-to="0" class="active"></button>

          {% for img in product.extra_images.all %}
          <button type="button" data-bs-target="#productCarousel" data-bs-slide-to="{{ forloop.counter }}"></button>
          {% endfor %}
        </div>

        <div class="carousel-inner" style="margin-top: 50px;">

          <div class="carousel-item active">
            <img src="{{ product.main_image.url }}" class="d-block w-100" style="height:380px; object-fit:contain;">
          </div>

          {% for img in product.extra_images.all %}
          <div class="carousel-item">
            <img src="{{ img.image.url }}" class="d-block w-100" style="height:380px; object-fit:contain;">
          </div>
          {% endfor %}
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#productCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#productCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon"></span>
        </button>

      </div>

      <div class="row my-1">

      </div>
    </div>

    <div class="col-md-8 my-4 description py-4 px-4">
      <h4><b id="namepr{{product.id}}">{{product.product_name}}</b></h4>
      {% if product.discount == 0 %}
      <p><b style="font-size: 20px;" id="pricepr{{product.id}}"
          class="text-success">{{product.finalPrice}}</b><b>&nbsp;₹</b>
        {% if product.prodRating %}
        <span class="badge bg-warning text-dark fs-6 mx-4" style="width:fit-content;"> ⭐ {{ product.prodRating}}/5</span>
        {% endif %}
      </p>
      {% else %}
      <p><b style="font-size: 20px;"
          class="text-danger text-decoration-line-through">{{product.price}}</b><b>&nbsp;₹</b> (-{{product.discount}} %)
        {% if product.prodRating %}
        <span class="badge bg-warning text-dark fs-6 mx-4" style="width:fit-content;"> ⭐ {{ product.prodRating}}/5</span>
        {% endif %}
      </p>
      <p><b style="font-size: 20px;" id="pricepr{{product.id}}"
          class="text-success">{{product.finalPrice}}</b><b>&nbsp;₹</b></p>
      {% endif %}
      <div class="descIn">
        <p>{{product.desc|safe}}</p>
      </div>
      {% if product.available_sizes %}
      <div class="mt-2 mb-3">
        <p class="fw-semibold mb-2">Available Sizes</p>

        <div class="d-flex flex-wrap gap-2">
          {% for size in product.available_sizes|cut:" "|split:"," %}
          {% if forloop.first%}
          <input type="radio" class="btn-check" name="selected_size{{product.id}}" id="size{{ forloop.counter }}" value="{{ size }}" autocomplete="off" checked>
          {% else %}
          <input type="radio" class="btn-check" name="selected_size{{product.id}}" id="size{{ forloop.counter }}" value="{{ size }}" autocomplete="off" >
          {% endif %}
          <label class="btn btn-outline-primary rounded-pill px-3 py-1" for="size{{ forloop.counter }}">
            {{ size }}
          </label>
          {% endfor %}
        </div>
      </div>
      {% endif %}

      <div style="display: flex; flex-direction: row; justify-content: center;" class="mt-auto">
        {% if request.user.is_authenticated %}
        <a class="divpr" href='/shop/checkout/?dummy=true' style="text-decoration: none;">
          <button class="btn btn-primary mx-2" type="submit" id="buyNow" style="width: 100%; height:100%;">Buy
            Now</button>
        </a>
        {% else %}
        <button type="button" class="btn btn-primary mx-2 divpr" data-toggle="modal" data-target="#loginModal">
          Buy Now
        </button>
        {% endif %}

        {% if request.user.is_authenticated %}
        <div id="divpr{{product.id}}" class="divpr">
          <button id="pr{{product.id}}" class="btn btn-primary cart mx-2" style="width: 100%;height:100%;">Add To
            Cart</button>
        </div>
        {% endif %}
      </div>
    </div>
  </div>


</div>
<hr class="w-75" style="align-items: center; margin: auto;">

<div class="container my-4 d-flex justify-content-center flex-column align-items-center">
  <h4>Rating <span class="star-rating" data-rating="{{product.prodRating}}" style="font-size: 40px;"></span> <span
      class="text-muted fs-6">(rated by : {{product.ratingCount}} customers)</span></h4>


  <form class="row g-3" action="/shop/rating/" method="post">
    {% csrf_token %}
    <div class="d-flex flex-column ">
      <input type="hidden" value="{{product.id}}" name="prodId">
      <label for="review" class="form-label">Review</label>
      <textarea name="review" id="review" rows="5" placeholder="Enter Your Review Here..." required></textarea>
    </div>
    <div class="col-12 d-flex flex-column ">
      <label for="rate" class="form-label">Rate</label>
      <select name="rate" id="rate" class="form-select d-flex justify-content-center" required>
        <option value="0" disabled selected>Give Rate</option>
        <option value="1">worst</option>
        <option value="2">Poor</option>
        <option value="3">Good</option>
        <option value="4">Very Good</option>
        <option value="5">Excelent</option>
      </select>
    </div>
    <div class="col-12 d-flex justify-content-center">
      <button type="submit" id="submitBtn" class="btn btn-primary" disabled>Submit</button>
    </div>

  </form>



</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-7">
      <h4 class="mt-4 text-center mb-4">Reviews</h4>
      <div class="card mb-3 shadow-sm">
        {% for r in product.rating_set.all %}
        <div class="card-body">

          <div class="d-flex justify-content-between align-items-center">
            <h6 class="mb-0 fw-bold text-primary">
              {{ r.user.username }}
            </h6>
            <span class="badge bg-warning text-dark fs-6">
              ⭐ {{ r.rating }}/5
            </span>
          </div>

          <p class="mt-2 mb-2 text-secondary">
            {{ r.review }}
          </p>

          <small class="text-muted">
            Reviewed on {{ r.created_at|date:"d M Y, h:i A" }}
          </small>

        </div>
        {% empty %}
        <p class="text-muted text-center">No reviews yet.</p>
        {% endfor %}

      </div>
    </div>
  </div>
</div>



{% endblock %}

{% block js %}
<script src="{% static 'shop/js/cart.js' %}"></script>
<script>
  
  let id = "pr{{ product.id }}";
  function updateCart(cart) {
    const divEl = document.getElementById('div' + id);
    if (divEl) {
      if (cart[id] && cart[id][0] > 0) {
        divEl.innerHTML =
          "<button id='minus" + id + "' class='btn btn-primary minus' style='height: 50px;width:50px;'>-</button> " +
          "<span id='val" + id + "' class='mx-4'>" + cart[id][0] + "</span> " +
          "<button id='plus" + id + "' class='btn btn-primary plus' style='height: 50px;width:50px;'> + </button>";
      } else {
        divEl.innerHTML =
          "<button id='" + id + "' class='btn btn-primary cart mx-2' style='width: 100%;height:100%;'>Add To Cart</button>";
        if (cart[id]) {
          delete cart[id];
        }
      }
    }

    let sum = 0;
    for (let item in cart) {
      sum += cart[item][0];
    }

    localStorage.setItem(cartKey, btoa(JSON.stringify(cart)));

    const cartBadge = document.getElementById('cart');
    if (cartBadge) {
      cartBadge.innerHTML = sum;
    }

    updatePopover(cart);
  }


  btn = document.getElementById('buyNow')
  btn.addEventListener("click", function () {
    let cartDummy = cartKey + "Dummy";
    const selected = document.querySelector('input[name="selected_size{{product.id}}"]:checked');
    let cart2 = {}
    if (cart[id] === undefined) {
      cart2[id] = [1, "{{product.product_name}}", parseFloat("{{product.finalPrice}}"),selected.value];
    }
    else {
      cart2[id] = cart[id];
      console.log(cartDummy);
      delete cart[id]
      localStorage.setItem(cartKey, btoa(JSON.stringify(cart)));
    }
    localStorage.setItem(cartDummy, btoa(JSON.stringify(cart2)));
  })

  const rateSelect = document.getElementById('rate');
  const submitBtn = document.getElementById('submitBtn');

  rateSelect.addEventListener('change', function () {
    if (this.value === "0") {
      submitBtn.disabled = true;
    } else {
      submitBtn.disabled = false;
    }
  });


</script>


{% endblock %}